routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('home', 'HomeController');
Route::resource('client', 'ClientController');
Route::resource('consultant', 'ConsultantController');
Route::resource('login', 'LoginController');
Route::resource('inner', 'InnerController');
Route::resource('vendors', 'VendorController');

Route::get('consultant/consultants_by_categorories_id', 'ConsultantController@consultantsByCategororiesId');

app/Consultant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Consultant extends Model
{
    protected $fillable = ['name', 'email', 'password', 'description', 'address', 'categories_id'];

    public function category()
    {
        return $this->belongsTo(Category::class, 'categories_id');
    }
}

app/Http/Controllers/ConsultantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Consultant;
use App\Category;

class ConsultantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('consultants.create',['categories' => Category::where('status', 1)->get() ]);
        /* 
        $consultants = Consultant::all();
        return view('index', compact('consultants')); 
        */
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('consultants.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required',
            'password' => 'required',
            'categories_id' => 'required'
        ]);
        $consultant = Consultant::create($validatedData);

        return redirect('/consultant')->with('success', 'Consultant is successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $consultant = Consultant::findOrFail($id);

        return view('edit', compact('Consultant'));
    }

    public function consultantsByCategororiesId()
    {
        $categories_id = Input::get('categories_id');
        $consultants = Consultant::where([ 'categories_id' => $categories_id ])->get();
        return view('consultants.select', ['consultants' => $consultants]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required',
            'password' => 'required',
        ]);
        Consultant::whereId($id)->update($validatedData);

        return redirect('/home')->with('success', 'Consultant is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $consultant = Consultant::findOrFail($id);
        $consultant->delete();

        return redirect('/home')->with('success', 'Consultant is successfully deleted');
    }
}

resources/views/consultants/create.blade.php
@extends('layouts.app')

@section('content')

<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
    <a href="/" class="logo mr-auto"><img src="./img/logo.png" alt="" class="img-fluid"></a>
    <nav class="nav-menu d-none d-lg-block"> 
        <ul>
        <li class="active"><a href="/home#hero">Início</a></li>
        <li><a href="/home#client">Cliente</a></li>
        <li><a href="/home#consult">Consultor</a></li>
        <li><a href="/home#vendor">Fornecedor</a></li>
        <li><a href="/home#contact">Contato</a></li>
        </ul>
    </nav>
    <a href="/login" class="appointment-btn scrollto" style="margin-right: 10px;">Entrar</a>
    </div>
</header>
    
<main id="main">
    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-8 mt-5 mt-lg-0 centro">
                <style>
                    .uper-title {
                        margin-top: 20%;
                    }
                    .uper {
                        margin-top: 40px;
                    }
                </style>
                <div class="uper-title">
                    <div class="section-title">
                        <h2>Cadastro de consultor</h2>
                        <p>Forneça o seu serviço de consultoria para uma grande base de clientes e amplie sua presença online se tornando um consultor certificado BridgeMaker! Atenda clientes de todo o Brasil atendendo remotamente os nichos de mercado que você domina.</p>
                    </div>
                </div>
                <div class="card uper">
                    <div class="card-body">
                        @if ( session('success') ) 
                            <div class="alert alert-success">
                                Consultor cadastrado com sucesso!
                            </div><br>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br>
                        @endif
                        <form method="post" action="{{ route('consultant.store') }}">
                            <div class="form-group">
                                @csrf
                                <label for="name">Nome *</label>
                                <input type="text" class="form-control" name="name"/>
                            </div>
                            <div class="form-group">
                                <label for="price">Email *</label>
                                <input type="email" class="form-control" name="email"/>
                            </div>
                            <div class="form-group">
                                <label for="quantity">Senha *</label>
                                <input type="password" class="form-control" name="password"/>
                            </div>
                            <div class="form-group">
                                <label for="categories_id">Categoria *</label>
                                <select class="form-control" id="categories_id" name="categories_id">
                                    <option value="">{{'Selecione uma categoria'}}</option>
                                    @if( $categories )
                                        @foreach( $categories as $category )
                                            <option value="{{$category->id}}">{{$category->description}}</option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<footer id="footer" style="position:absolute;bottom:0;width:100%;">
    <div class="container d-md-flex py-4">
    <div class="mr-md-auto text-center text-md-left">
        <div class="copyright">
        &copy; Copyright <strong><span>Bridge Maker</span></strong>. Todos os direitos reservados
        </div>
    </div>
</footer>
@endsection

resources/views/consultants/select.blade.php
<label for="consultants_id"> {{ 'Consultores' }} *</label>
<select class="form-control" id="consultants_id" name="consultants_id">
    <option value="">{{'Selecione um consultor' }}</option>
    @if( ! $consultants->isEmpty() )
        @foreach( $consultants as $consultant )
            <option value="{{$consultant->id}}">{{$consultant->name}}</option>
        @endforeach
    @endif
</select>